<?php 
$prevDir = "";
$pageName = "index.php";
include "php/logControl/loginControl.php";
?>
<!DOCTYPE html>
<html lang="it">
<head>
	<meta charset="utf-8">
      <title>Repository studenti</title>
      <link rel="stylesheet" type="text/CSS" href="css/themes/dark.css" id="theme">
      <link rel="stylesheet" type="text/CSS" href="css/general.css">
      <link rel="stylesheet" type="text/CSS" href="css/header.css">
      <link rel="stylesheet" type="text/CSS" href="css/navbar.css">
      <link rel="stylesheet" type="text/CSS" href="css/footer.css">
      <link rel="icon" type="image/ICO" href="media/.ico/cherubino_pant541.ico">
      <script src="js/themeControl.js"></script>
      <script src="js/logControl/logout.js"></script>
</head>
<body>
      <header>
            <p>Biblioteca UniPi</p>
            <p>Raccolta di appunti degli studenti per gli studenti</p>
            <p>proprio quella</p>
            <img src="media/.svg/logo_white.svg" alt="logo UniPi">
      </header>

      <nav>
            <a href="index.php" class="navbarElement currentPage"><div>&#x2302; &#x1F3E0; Home</div></a>
            <a href="personal.php" class="navbarElement"><div>&#128193; Area personale</div></a>
            <a href="search.php" class="navbarElement"><div>&#x1F50E; &#xFE0E; Cerca</div></a>
            <a href="login.php" class="navbarElement"><div>&#9094; Login</div></a>
            <a href="signup.php" class="navbarElement"><div>Registrati</div></a>
            <a href="manual.html" class="navbarElement"><div>&#128214; Manuale</div></a>
            <a href="documentation.php" class="navbarElement"><div>&#128202; Doc-</div></a>
            <div class="navbarElement navbarDropDown">
                  &#127912; Tema
                  <div class="themeOptionsContainer">
                        <a class="themeOption" onclick="setTheme('dark')">Scuro</a>
                        <a class="themeOption" onclick="setTheme('grey')">Grigio</a>
                        <a class="themeOption" onclick="setTheme('light')">Chiaro</a>
                        <a class="themeOption" onclick="setTheme('pantone')">Pantone</a>
                        <a class="themeOption" onclick="setTheme('custom')">Neon</a>
                  </div>
            </div>
            <div class="navbarElement logoutElement" onclick="logout()"><span>&#11199; &#9211;</span> Logout</div>
      </nav>

      <script>
            window.addEventListener('scroll', function() {
                  const scroll = window.scrollY;
                  document.querySelector('header').style.backgroundPositionY = -0.5 * scroll + 'px';
            });
      </script>
      <article>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec auctor turpis, sit amet porttitor metus. Vestibulum maximus nibh eget sapien fermentum sodales. Maecenas id felis vel purus ullamcorper pulvinar a ac tellus. Nam vel volutpat est. Mauris consectetur ipsum libero, quis lacinia neque accumsan quis. Donec a metus nec enim volutpat venenatis nec sed metus. Vivamus eu purus auctor, blandit turpis ac, accumsan magna. Quisque molestie nunc nibh, sed iaculis nisi elementum in. Pellentesque vel volutpat lectus, et aliquam purus. Integer egestas odio in lacus dictum vulputate. Pellentesque luctus dapibus urna efficitur sollicitudin. Duis tempus euismod commodo. Mauris ultrices interdum blandit.
Duis a erat augue. Vivamus a mauris magna. Proin ac libero at risus hendrerit lobortis nec sed velit. Duis ac arcu nisl. Vestibulum eget risus quam. In in libero a est lobortis pellentesque. Donec gravida faucibus massa, sed mollis magna luctus a. Pellentesque pellentesque suscipit velit, sed bibendum magna porta id. Suspendisse potenti. Etiam eleifend sapien vel interdum pharetra. Aliquam ipsum elit, molestie vel venenatis nec, dictum eget lectus. Quisque commodo, dui a malesuada pretium, nisl augue euismod ex, in eleifend lacus arcu et lectus. Nulla vitae risus sed neque hendrerit faucibus eu a diam. Aliquam ornare nibh in nulla luctus efficitur. Curabitur in purus justo.
Sed quis aliquam eros. Quisque commodo lacus eget finibus dictum. Fusce neque nisl, pharetra laoreet fermentum a, malesuada nec massa. Nullam in aliquet ligula. Nulla et tortor sit amet metus bibendum tempor. Pellentesque eu nibh mauris. Fusce nec elit sem. Quisque luctus vulputate ligula, sed viverra tellus feugiat malesuada. Nunc varius, est pellentesque convallis convallis, tellus augue dignissim urna, at eleifend ante tortor nec magna.
Cras purus mi, sodales ut lectus blandit, venenatis aliquet nisl. In hac habitasse platea dictumst. Mauris laoreet sagittis leo, et mollis dolor interdum ut. Nulla aliquet odio orci, a pharetra sem rutrum quis. Vivamus eget lectus eu tortor mollis venenatis. Aenean laoreet augue lectus, vitae blandit risus aliquam id. Aliquam non arcu cursus, consectetur orci ut, volutpat erat. Curabitur id massa molestie, lacinia tellus nec, malesuada libero. Vivamus condimentum sem vitae mattis tincidunt. Nam maximus lobortis maximus. Vestibulum nibh purus, rhoncus vel congue eget, tristique in libero. Sed consequat tincidunt malesuada. Donec auctor eros arcu, posuere pretium quam vulputate nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in laoreet libero. Donec dapibus ultrices nisl.
Mauris arcu lorem, elementum nec sem id, mollis condimentum elit. Nulla a tempus eros. Pellentesque et ultricies magna. In nec ligula eu quam placerat lacinia ac sed elit. Duis pulvinar magna eu nulla varius rutrum. Ut lacus magna, interdum at blandit non, hendrerit ac magna. Pellentesque aliquam sollicitudin odio. Cras eu eleifend ex. Morbi dapibus, tellus in cursus vestibulum, erat nunc hendrerit lorem, a malesuada lectus eros ullamcorper est. Phasellus non finibus ante. Cras mattis mollis odio, sed elementum lacus accumsan quis.
Etiam velit eros, vestibulum vel ipsum et, pellentesque eleifend eros. Vestibulum id nulla metus. Pellentesque posuere ut urna sit amet eleifend. Pellentesque lacinia consectetur auctor. Sed eu lectus nec erat elementum efficitur quis et diam. Maecenas tincidunt magna et tellus fermentum bibendum. Etiam pellentesque, dui at placerat maximus, mi metus iaculis diam, ac fringilla felis augue eget risus. Aliquam a nisi ullamcorper, varius risus vitae, rutrum massa. Quisque neque lorem, aliquet et malesuada in, vehicula ac mauris. Vestibulum faucibus gravida purus id maximus. Curabitur blandit laoreet auctor. Nam sed odio ut neque elementum tincidunt. Pellentesque tincidunt imperdiet risus vel tempor.
Vivamus vitae turpis eu tellus pretium elementum nec id lacus. Etiam eu mi lacinia, aliquet metus at, viverra erat. Praesent et vehicula quam. Duis quis odio mattis, iaculis tortor id, posuere lacus. Aenean ullamcorper commodo varius. Mauris ut leo convallis enim rutrum dictum pharetra vitae enim. Integer rutrum quis magna quis consequat. Nunc eros nisi, pharetra sollicitudin quam id, egestas egestas enim. Aenean consectetur tincidunt dui sit amet tincidunt. Donec et cursus ipsum. Curabitur sed bibendum nunc. Curabitur ut dictum purus, id laoreet diam. Donec commodo nunc erat. Vestibulum sodales, ex ac suscipit dignissim, sem ante tempor arcu, et mattis risus eros non neque.
Sed pharetra massa elit, ac porta lectus facilisis elementum. Etiam suscipit consectetur mauris, et efficitur dui feugiat sit amet. Ut euismod eros et pharetra hendrerit. Sed facilisis ligula ut tempor cursus. Cras a lobortis lorem, id ullamcorper leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam et maximus eros.
Donec mollis turpis turpis, et ultrices urna elementum id. Nullam varius ornare enim ut fermentum. Cras purus lorem, ornare id nisi at, finibus dapibus ex. Duis eget malesuada mauris. Ut scelerisque leo sed suscipit sagittis. Duis congue, urna id placerat consequat, nulla mauris tristique massa, nec tincidunt metus erat at est. Sed commodo eleifend lectus nec consectetur. Etiam est lectus, dignissim in commodo at, aliquet vehicula velit. Sed iaculis auctor imperdiet. Integer vel est commodo, convallis massa sit amet, placerat enim. Vestibulum scelerisque consectetur sollicitudin. Phasellus tincidunt est viverra ante euismod sodales.
Nam id diam hendrerit neque vulputate sagittis nec elementum neque. Sed id lacinia nulla. Nulla quam eros, tincidunt eu sapien vitae, dapibus tristique nunc. Nullam mattis augue sit amet velit feugiat condimentum. Ut cursus felis pharetra magna iaculis, a ultricies nisl tristique. Nulla laoreet commodo dolor, id aliquam sapien posuere id. Aenean in auctor risus.
Aliquam molestie est lacus, nec pharetra nibh dignissim at. In suscipit eu ligula ac efficitur. Vestibulum suscipit metus nec nunc facilisis egestas. Nulla facilisi. Pellentesque dolor nisi, viverra vel dictum nec, mollis placerat nisi. Morbi imperdiet, augue quis commodo tempus, lectus est tristique dolor, quis sodales metus nibh id lectus. Aliquam at condimentum magna. Nulla euismod mi in quam sollicitudin, ac dapibus nisl aliquam. Sed nec libero eget ex blandit molestie. Nunc efficitur, felis sit amet pretium cursus, tellus dui feugiat erat, sed convallis orci ligula sit amet nisl. Vestibulum elementum diam est, nec eleifend felis egestas id. Aliquam interdum non odio id gravida. Quisque sagittis, magna nec elementum commodo, metus libero pharetra massa, sit amet tincidunt nunc urna at eros.
Vivamus vitae efficitur libero. Vivamus nec tincidunt sem.<h1> Suspendisse</h1> id nunc eget arcu sollicitudin varius. Cras at dui a sapien auctor dapibus ac sed arcu. Nullam ac ullamcorper turpis, nec malesuada nisi. Duis sagittis justo sem, sed ullamcorper diam faucibus vel. Cras tempor mattis mauris sed viverra. Aenean rhoncus dictum felis, vitae congue orci volutpat bibendum. Nullam et ante diam. Mauris neque enim, tincidunt ac massa eu, scelerisque dapibus magna. Quisque at augue metus. Curabitur tempor, libero eu consequat tempus, elit nulla vehicula massa, nec rutrum risus diam non ex. Interdum et malesuada fames ac ante ipsum primis in faucibus.
Cras molestie, ante nec eleifend ultrices, dui neque euismod ex, vel tempor nisl lorem eu elit. Quisque vehicula bibendum convallis. Sed quis ornare tellus. Duis sagittis, augue ac rhoncus cursus, est risus volutpat ipsum, sed faucibus dolor est convallis nunc. In consequat purus vel eros suscipit ornare. Etiam suscipit gravida odio euismod scelerisque. Fusce rutrum, nibh vel lobortis bibendum, dolor nunc egestas mi, ut efficitur lorem mi quis nisi. Phasellus dictum justo sed metus accumsan, non vulputate sem dignissim. Vestibulum placerat nisi quis arcu pharetra, posuere ultricies justo volutpat. Vestibulum ac mauris vel justo tempus elementum in at lorem. Nullam dolor nisl, molestie eget gravida vel, accumsan aliquam turpis. Etiam cursus ante nec maximus convallis. Vestibulum sagittis tellus ac pharetra sollicitudin. Praesent ac egestas turpis.
Sed est massa, scelerisque a consectetur nec, semper vel mauris. Mauris at fringilla mauris, in convallis risus. Etiam posuere ac odio id aliquet. Pellentesque turpis lorem, malesuada nec dignissim quis, scelerisque et dui. Mauris hendrerit augue at magna rutrum, in tempus mauris tincidunt. Maecenas aliquam velit ultricies, imperdiet orci ac, vulputate dolor. In mattis diam tortor, in auctor ex elementum in. Proin et porttitor ante. Duis ut lacus ante. Etiam commodo tincidunt libero, a placerat ligula condimentum id. Fusce et dolor ac purus mollis bibendum volutpat in nunc. Quisque vitae tellus ut lectus imperdiet pharetra imperdiet id enim. In a purus non nibh pulvinar fringilla.
Duis interdum risus egestas metus venenatis, eget tristique lorem aliquet. Donec congue nec ligula et tincidunt. Phasellus maximus fermentum nibh, a pulvinar urna mollis sit amet. Proin ultrices metus elit, et vestibulum lorem porta ut. Sed varius erat eget dui accumsan scelerisque. Suspendisse potenti. Nulla sed arcu eu ipsum dignissim venenatis. Nullam consequat magna at luctus egestas. Mauris nisi est, molestie id vulputate vel, dapibus quis ipsum. Curabitur ac magna eu ligula posuere aliquam. Proin commodo venenatis purus, vitae ultricies odio auctor ut. Mauris viverra, nunc vitae semper suscipit, nisl turpis efficitur ligula, quis efficitur elit nunc eget lorem. Donec suscipit in ipsum vel tincidunt.
Maecenas aliquam erat posuere commodo tempor. Maecenas vitae ligula sollicitudin, pellentesque nisi eget, gravida urna. Proin et ex vel urna finibus suscipit. In non arcu consectetur, tincidunt sapien eu, accumsan tellus. Nulla lectus nulla, feugiat a tortor nec, pretium fringilla est. Fusce vel leo neque. Pellentesque cursus tempus diam dapibus efficitur. Integer lorem nibh, facilisis ac tincidunt nec, condimentum eget lorem. Praesent dui metus, consectetur id volutpat eu, dignissim at felis.
Aliquam ultricies neque sit amet turpis venenatis, quis blandit purus consectetur. Pellentesque blandit aliquam tellus, in blandit elit porta quis. Sed ac convallis risus, a sagittis mauris. Curabitur tempor, magna vitae tincidunt interdum, ex justo dapibus mauris, ullamcorper dictum est metus sed libero. Phasellus eleifend euismod tellus, nec bibendum metus. Nunc at diam elit. Donec posuere orci in magna eleifend iaculis. Nunc elementum pharetra tempor. Sed mi ex, interdum nec bibendum nec, bibendum vitae ligula. Praesent arcu neque, lobortis ac metus et, molestie luctus nibh. Quisque ut libero et ligula interdum semper. Duis vestibulum tellus vitae quam posuere mollis. Curabitur tempus tempor lacus, id commodo dui ullamcorper non. Donec eleifend augue nec tellus suscipit lobortis vitae ut justo. Integer consectetur, urna eget auctor tristique, nisi nibh suscipit enim, ac bibendum nunc risus eu erat.
Praesent sodales dictum ullamcorper. Morbi vitae mi quis libero commodo consequat. Nulla facilisi. Nullam luctus non lectus sit amet fermentum. Nunc non tellus facilisis justo egestas dictum. Curabitur nisl neque, cursus at vestibulum ut, molestie nec nibh. Phasellus sit amet erat id ipsum dapibus facilisis. Maecenas sit amet dolor a turpis dapibus dignissim. Nam et fringilla est, vel pharetra nulla. Etiam urna leo, tempor a lorem id, aliquam efficitur orci. Cras non ex volutpat, laoreet turpis laoreet, fringilla urna. Aenean lectus ante, sodales scelerisque justo venenatis, vehicula aliquam risus. Nullam ac diam vestibulum, congue risus a, vulputate risus. Maecenas sed leo non mi gravida cursus bibendum ut est. Sed suscipit ornare felis at maximus.
Vivamus viverra consequat nulla, non aliquet massa pharetra ac. Quisque condimentum nec libero ut gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sed lacus pulvinar turpis rhoncus feugiat eu nec lorem. In in tellus sem. Donec a scelerisque ligula. Pellentesque pretium est eget velit iaculis, sit amet aliquet lorem pulvinar. Vestibulum volutpat lectus sit amet ex rhoncus, ut lacinia sapien venenatis. Quisque fringilla tempus orci vel tincidunt. Donec accumsan dignissim ligula, eu tempus magna dignissim vitae. Aenean facilisis metus eu maximus consequat. Phasellus est nisi, venenatis non quam non, pellentesque faucibus augue. Aenean ac dui bibendum felis mollis pretium. Ut vitae interdum purus.
Aliquam pretium, dolor id egestas condimentum, mi ligula aliquam quam, sed euismod ante diam non mi. Nullam pellentesque, metus id feugiat imperdiet, tortor purus dignissim libero, sed scelerisque ex felis vel nunc. Phasellus tempor pharetra sodales. Praesent non tincidunt mauris, non pretium ex. Suspendisse potenti. Phasellus pretium nec mi id ultricies. Suspendisse ut tempor urna. Aenean id arcu mi.
Quisque mauris sapien, molestie nec mattis ut, malesuada in enim. Nunc gravida, magna sed volutpat venenatis, purus nulla tempor lectus, id ornare enim nisi id magna. Aliquam erat volutpat. Donec viverra lacus ut mauris dictum, eget viverra mauris mollis. Morbi lacinia magna dui, vitae aliquam ligula facilisis non. Integer non ante at nibh pretium congue. Morbi eget hendrerit sem, ac malesuada nunc. Morbi quis pretium elit.
In faucibus egestas diam, ac lacinia tortor iaculis in. Proin scelerisque velit vel tincidunt eleifend. Aliquam at lobortis neque, quis varius est. Quisque ornare tempus velit. Praesent ante risus, pretium in turpis ac, imperdiet pretium quam. Vestibulum id mi efficitur, aliquet urna aliquet, tempor odio. Aenean enim justo, malesuada a elementum in, venenatis non sem. Nulla ut orci vitae ex luctus vulputate in sit amet justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean efficitur, tortor sit amet imperdiet pharetra, felis dolor pretium arcu, maximus pretium ex sem vel diam. Aenean id pretium velit, eu blandit mauris. Suspendisse egestas libero nec felis molestie fringilla. Suspendisse auctor magna id elit sodales, sed cursus nibh gravida. Quisque pulvinar enim eu elit accumsan laoreet.
Maecenas ornare vel magna a vestibulum. Aliquam nec est enim. Cras eleifend venenatis leo, vel ornare velit tempus tempus. Nulla in varius leo. Aliquam vestibulum pretium urna ac scelerisque. Sed eleifend consequat velit vel aliquet. Donec rhoncus id velit id lacinia. Pellentesque et fringilla nisl. Proin venenatis ut purus condimentum cursus. Duis eu lacus nec nunc dictum vulputate vitae ac odio. Sed efficitur purus at velit iaculis placerat. Ut vel vehicula nisl. Quisque porttitor, eros sed egestas convallis, eros tortor consequat urna, nec hendrerit lacus felis vel arcu. Cras diam magna, aliquet ac euismod vel, viverra a turpis. In sagittis eleifend euismod.
In mattis blandit odio, ut tempus diam porta sit amet. Donec eget orci non dolor feugiat lacinia. Donec orci augue, imperdiet a tempor quis, malesuada eget purus. Etiam lorem ex, efficitur in ante sit amet, rutrum cursus quam. Ut at accumsan tellus. Quisque laoreet risus non magna varius, in ultricies metus suscipit. Fusce lectus tellus, bibendum sed turpis et, porta commodo quam. Ut dictum id lacus vel dapibus. Nullam eleifend vehicula sapien vel suscipit. Maecenas purus libero, venenatis vitae fermentum et, porttitor dapibus purus. Ut sagittis nisl ut nunc volutpat commodo eu a nibh. Ut consectetur velit eget arcu dictum gravida eu at mi. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus.
      </article>

      <footer>
            Alessio Simoncini 2023
            Ingegneria Informatica [LT], DII
      </footer>
</body>
</html>